# WARNING: In swarm mode it is not possible to build an image during deployment
#         so the image must be built before deploying the stack
version: '3.9'


services:
  terra:
    build: .
    ports:
      - "3000:3000"
    environment:
      - GPT_API_KEY=your-api-key
      - MAPS_API_KEY=your-api-key
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure